version: '3.8'

services:
  db:
    image: postgres:14
    networks:
      - my_network
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: my-todo-container
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - .:/usr/src/app
    command: 'uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload'

    networks:
      - my_network
  
networks:
  my_network:
    driver: bridge

volumes:
  postgres_data: